export enum SwapType {
  ERC20_MAIN = 'ERC20->MAINNET',
  MAIN_ERC20 = 'MAINNET->ERC20',
  BINANCE_MAIN = 'BINANCE->MAINNET',
  MAIN_BINANCE = 'MAINNET->BINANCE',
  ERC20_BINANCE = 'ERC20->BINANCE',
}
